// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnHrS6et11SEHEekQjXMNAtAGH-KDV0JI',
    appId: '1:848644210356:web:7cfc354085e2b2e42ba1e1',
    messagingSenderId: '848644210356',
    projectId: 'flavour-test-51686',
    authDomain: 'flavour-test-51686.firebaseapp.com',
    storageBucket: 'flavour-test-51686.appspot.com',
    measurementId: 'G-W1BXSKJJ8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHFWPsy3V0XhRI5I7nX3KivviumWHz5_E',
    appId: '1:848644210356:android:e3e80540c49565e72ba1e1',
    messagingSenderId: '848644210356',
    projectId: 'flavour-test-51686',
    storageBucket: 'flavour-test-51686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgj5ebGQOCEk0jbakRqLRNlOQHvOqxYSI',
    appId: '1:848644210356:ios:9e7e2d73501e49002ba1e1',
    messagingSenderId: '848644210356',
    projectId: 'flavour-test-51686',
    storageBucket: 'flavour-test-51686.appspot.com',
    androidClientId: '848644210356-q2f1ljk126qqqhulq60jna4e09m5f8li.apps.googleusercontent.com',
    iosClientId: '848644210356-hbegkg03bg6ourrav9l9l9nc83vttbvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgj5ebGQOCEk0jbakRqLRNlOQHvOqxYSI',
    appId: '1:848644210356:ios:d267001a406fe1782ba1e1',
    messagingSenderId: '848644210356',
    projectId: 'flavour-test-51686',
    storageBucket: 'flavour-test-51686.appspot.com',
    androidClientId: '848644210356-q2f1ljk126qqqhulq60jna4e09m5f8li.apps.googleusercontent.com',
    iosClientId: '848644210356-ps4ckb2cp28hjrj8ken3fdi9csb4osbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackr',
  );
}
