// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Sgs3HC1ZRrtjxnvsYen9ZdUdr1HMdTI',
    appId: '1:891890956990:web:ce2e8026af813953c4bcef',
    messagingSenderId: '891890956990',
    projectId: 'expense-tracker-ea663',
    authDomain: 'expense-tracker-ea663.firebaseapp.com',
    storageBucket: 'expense-tracker-ea663.appspot.com',
    measurementId: 'G-QKRL0TE0YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPuZfWXWm2IQUTIRLGXjpi4jlRjY7QCZ4',
    appId: '1:891890956990:android:680e73c92538dc82c4bcef',
    messagingSenderId: '891890956990',
    projectId: 'expense-tracker-ea663',
    storageBucket: 'expense-tracker-ea663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdBy5xnSZPiBvm3xkHZJn0u2RM2fJ2WMw',
    appId: '1:891890956990:ios:c553af4e76391a9dc4bcef',
    messagingSenderId: '891890956990',
    projectId: 'expense-tracker-ea663',
    storageBucket: 'expense-tracker-ea663.appspot.com',
    androidClientId: '891890956990-4t1004pnlt15loha3eoe38fs351tsn31.apps.googleusercontent.com',
    iosClientId: '891890956990-2opbmlmaofck2bdf1t0hv1a3efv1sqr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdBy5xnSZPiBvm3xkHZJn0u2RM2fJ2WMw',
    appId: '1:891890956990:ios:b1a120afe790db48c4bcef',
    messagingSenderId: '891890956990',
    projectId: 'expense-tracker-ea663',
    storageBucket: 'expense-tracker-ea663.appspot.com',
    androidClientId: '891890956990-4t1004pnlt15loha3eoe38fs351tsn31.apps.googleusercontent.com',
    iosClientId: '891890956990-m2si9t71m9nmr0dh26cv251kgpvr50rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackr',
  );
}
