// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Sgs3HC1ZRrtjxnvsYen9ZdUdr1HMdTI',
    appId: '1:891890956990:web:c277ac019ce2652dc4bcef',
    messagingSenderId: '891890956990',
    projectId: 'expense-tracker-ea663',
    authDomain: 'expense-tracker-ea663.firebaseapp.com',
    storageBucket: 'expense-tracker-ea663.appspot.com',
    measurementId: 'G-17JDVYNSCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPuZfWXWm2IQUTIRLGXjpi4jlRjY7QCZ4',
    appId: '1:891890956990:android:8c0293b3949216afc4bcef',
    messagingSenderId: '891890956990',
    projectId: 'expense-tracker-ea663',
    storageBucket: 'expense-tracker-ea663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdBy5xnSZPiBvm3xkHZJn0u2RM2fJ2WMw',
    appId: '1:891890956990:ios:e379805eb065ceeec4bcef',
    messagingSenderId: '891890956990',
    projectId: 'expense-tracker-ea663',
    storageBucket: 'expense-tracker-ea663.appspot.com',
    iosClientId: '891890956990-m2si9t71m9nmr0dh26cv251kgpvr50rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdBy5xnSZPiBvm3xkHZJn0u2RM2fJ2WMw',
    appId: '1:891890956990:ios:e379805eb065ceeec4bcef',
    messagingSenderId: '891890956990',
    projectId: 'expense-tracker-ea663',
    storageBucket: 'expense-tracker-ea663.appspot.com',
    iosClientId: '891890956990-m2si9t71m9nmr0dh26cv251kgpvr50rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackr',
  );
}
